# Generated by Django 2.2.7 on 2019-11-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_app.Subject', verbose_name='subject'),
        ),
        migrations.CreateModel(
            name='Url_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url_link', models.URLField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_links', to='knowledge_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='knowledge_app.Subject')),
            ],
        ),
    ]
