# Generated by Django 2.2.7 on 2019-12-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0003_auto_20191202_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='url_link',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block', to='knowledge_app.Subject')),
            ],
        ),
    ]
