# Generated by Django 2.2.7 on 2019-12-03 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0004_auto_20191203_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeblock',
            name='code_langauge',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
