# Generated by Django 2.2.7 on 2019-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0006_remove_codeblock_code_langauge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_link',
            name='url_link',
            field=models.CharField(max_length=200),
        ),
    ]
